module.exports = {
  apps: require('./apps'),
  build: require('./build'),
  collaborate: require('./collaborate'),
  convert: require('./convert'),
  delete: require('./delete'),
  deprecate: require('./deprecate'),
  describe: require('./describe'),
  env: require('./env'),
  help: require('./help'),
  history: require('./history'),
  invite: require('./invite'),
  link: require('./link'),
  login: require('./login'),
  logs: require('./logs'),
  migrate: require('./migrate'),
  promote: require('./promote'),
  push: require('./push'),
  register: require('./register'),
  scaffold: require('./scaffold'),
  test: require('./test'),
  upload: require('./upload'),
  validate: require('./validate'),
  watch: require('./watch')
};
