module.exports = {
  help: require('./help'),
  login: require('./login'),
  logout: require('./logout'),
  init: require('./init'),
  register: require('./register'),
  scaffold: require('./scaffold'),
  describe: require('./describe'),
  watch: require('./watch'),
  test: require('./test'),
  link: require('./link'),
  apps: require('./apps'),
  versions: require('./versions'),
  validate: require('./validate'),
  build: require('./build'),
  upload: require('./upload'),
  push: require('./push'),
  promote: require('./promote'),
  migrate: require('./migrate'),
  deprecate: require('./deprecate'),
  collaborate: require('./collaborate'),
  invite: require('./invite'),
  history: require('./history'),
  logs: require('./logs'),
  env: require('./env'),
  convert: require('./convert')
};
